# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]

rssFullContent = true
favicon = "/img/labixiaoxin.jpg"

SortBy = "default"


[footer]
since = 2026
customText = "Powered by Hugo & Stack"


[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02"


#####################
# 左侧边栏
#####################

[sidebar]

emoji = "🔞"

subtitle = "Beihang University<br>Xi'an Jiaotong University<br>Honor"

avatar = "/img/labixiaoxin.jpg"


#####################
# 文章设置
#####################

[article]

headingAnchor = true

math = true

readingTime = true


[article.license]

enabled = false


#####################
# 首页组件
#####################

[widgets]

homepage = [

    { type = "search" },

    { type = "archives", params = { limit = 10 } },

    { type = "categories", params = { limit = 10 } },

    { type = "tag-cloud", params = { limit = 20 } },

]


page = [{ type = "toc" }]


#####################
# 深色模式
#####################

[colorScheme]

toggle = true

default = "auto"


#####################
# 评论
#####################

[comments]

enabled = false
provider = ""
